# Server configuration
server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kaemusic
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=9a676786a7d5ea5a2a95c9a7d5ea5c2a95c9a7d5ea5c2a95c9a7d5ea5c2a95c9a7d5
jwt.expiration=86400000
